---

- name: include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: allow connections to ovn central services port 6641 and 6642
  become: yes
  firewalld:
    zone: public
    port: 6641-6642/tcp
    permanent: yes
    state: enabled
  when: install_central

- name: restart firewalld
  become: yes
  systemd:
    state: reloaded
    daemon_reload: yes
    name: firewalld
  when: install_central

- name: install OVN node packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: '{{ ovn_node_packages }}'
  when: install_node

- name: install OVN central packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: '{{ ovn_central_packages }}'
  when: install_central

#- name: ensure OVN services are started and enabled on boot when using the systemd module
#  become: yes
#  systemd:
#    name: "{{ item }}"
#    enabled: yes
#    state: started
#  with_items: "{{ ovn_services }}"
#  when: 'ansible_os_family == "Debian"'

# systemd module is non-functional for CentOS
- name: ensure OVN central services are started usign the command module
  become: yes
  command:
    argv:
      - systemctl
      - enable
      - --now
      - "{{ item }}"
  with_items: "{{ ovn_central_services }}"
  when: install_central

- name: ensure OVN node services are started usign the command module
  become: yes
  command:
    argv:
      - systemctl
      - enable
      - --now
      - "{{ item }}"
  with_items: "{{ ovn_node_services }}"
  when: install_node
