---

- name: include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: install OVN packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: '{{ ovn_packages }}'

- name: ensure OVN services are started and enabled on boot when using the systemd module
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ ovn_services }}"
