---

ovn_node_packages:
  - 'ovn'
  - 'ovn-host'
  - 'ovn-vtep'

ovn_node_services:
  - "ovn-controller-vtep"
  - "ovn-controller"

ovn_central_packages:
  - 'ovn-central'

ovn_central_services:
  - "ovn-northd"
