---
galaxy_info:
  #role_name: libvirt_vm
  author: Mark Goddard
  description: >
    Role to configure and create VMs on a Libvirt/KVM hypervisor
  company: StackHPC Ltd
  license: Apache2
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - cloud
    - kvm
    - libvirt
    - vm

dependencies: []
