---

- name: include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: install openvswitch packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: '{{ ovs_packages }}'

- name: ensure ovs services are started and enabled on boot
  service:
    name: "{{ item }}"
    state: "started"
    enabled: true
    use: service
  with_items: "{{ ovs_services }}"
