---

- name: include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: install openvswitch packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: '{{ ovs_packages }}'

- name: ensure ovs services are started and enabled on boot when using the systemd module
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ ovs_services }}"
  when: 'ansible_os_family == "Debian"'

# systemd module is erroring out for CentOS
- name: ensure OVN services are started usign the command module
  become: yes
  command:
    argv:
      - systemctl
      - enable
      - --now
      - "{{ item }}"
  with_items: "{{ ovs_services }}"
  when: 'ansible_os_family == "RedHat"'
