---

- name: enable vnc-service
  become: yes
  firewalld:
    service: vnc-server
    permanent: yes
    state: enabled

- name: post task restart firewalld
  systemd:
    state: restarted
    daemon_reload: yes
    name: firewalld
