---

# https://www.osradar.com/how-to-install-open-vswitch-on-centos-8-rhel-8/
ovs_packages:
  - 'epel-release'
  - 'centos-release-openstack-train'
  - 'openvswitch'
  - 'libibverbs'

ovs_services:
  - "openvswitch"
