---

- name: enable vnc-server service
  become: yes
  firewalld:
    service: vnc-server
    permanent: yes
    state: enabled

- name: post task restart firewalld
  systemd:
    state: restarted
    daemon_reload: yes
    name: firewalld

# the below fails due to psutil not being able to be installed on target machine 
#- name: disable vnc encryption
#  dconf:
#    key: "/org/gnome/desktop/remote-desktop/vnc"
#    value: "['none']"
#    state: present

- name: disable vnc encryption using the command module
  command:
    argv:
      - /usr/bin/gsettings
      - list-recursively
      - org.gnome.desktop.remote-desktop.vnc
  register: cmd_out_get

- debug: var=cmd_out_get

- name: disable vnc encryption using the command module
  become: yes
  command:
    argv:
      - /usr/bin/gsettings
      - set
      - org.gnome.desktop.remote-desktop.vnc
      - encryption
      - ['none']
  register: cmd_out_set

- debug: var=cmd_out_set

- name: disable vnc encryption using the command module
  command:
    argv:
      - /usr/bin/gsettings
      - list-recursively
      - org.gnome.desktop.remote-desktop.vnc
  register: cmd_out_gett

- debug: var=cmd_out_gett

- name: disable SELinux
  selinux:
    state: disabled
  register: selinux_task_result

- name: reboot for SELinux changes to take effect
  reboot:
    msg: "reboot initiated for SELinux changes to take effect"
  when: selinux_task_result.reboot_required
