---

- name: enable vnc-server service
  become: yes
  firewalld:
    service: vnc-server
    permanent: yes
    state: enabled

- name: post task restart firewalld
  systemd:
    state: restarted
    daemon_reload: yes
    name: firewalld

- name: disable SELinux
  selinux:
    state: disabled
  register: selinux_task_result

- name: reboot for SELinux changes to take effect
  reboot:
  when selinux_task_result.reboot_required = true
