# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

#ntp_timezone: 'UTC'
ntp_timezone: 'America/Chicago'
ntp_packages:
ntp_service_name:
ntp_service_state: 'started'
ntp_service_enabled: yes
ntp_conf_template: 'ntp.j2'
ntp_drift_file: '/var/lib/ntp/ntp.drift'
ntp_statistics_dir:
ntp_statistics: 'loopstats peerstats clockstats'
ntp_file_generation_sets:
  - 'filegen loopstats file loopstats type day enable'
  - 'filegen peerstats file peerstats type day enable'
  - 'filegen clockstats file clockstats type day enable'
ntp_servers:
  - '0.ubuntu.pool.ntp.org'
  - '1.ubuntu.pool.ntp.org'
  - '2.ubuntu.pool.ntp.org'
  - '3.ubuntu.pool.ntp.org'
  - 'ntp.ubuntu.com'
ntp_restrictions:
  - 'restrict -4 default kod notrap nomodify nopeer noquery'
  - 'restrict -6 default kod notrap nomodify nopeer noquery'
  - 'restrict 127.0.0.1'
  - 'restrict ::1'
