---

- name: install firewalld needed for vnc service setup
  become: yes
  package:
    name: firewalld
    state: present

#- name: install psutil python package needed for vnc service setup
#  pip:
#    name: psutil
