---

- name: include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: install OVN node packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: '{{ ovn_node_packages }}'

- name: ensure OVN node services are started usign the command module
  become: yes
  command:
    argv:
      - systemctl
      - enable
      - --now
      - "{{ item }}"
  with_items: "{{ ovn_node_services }}"
