---

# Who owns the serial console logs in console_log_path
libvirt_vm_log_owner: libvirt-qemu

# The environment passed to virt_volume.sh
libvirt_vm_script_env_debian:
  VOLUME_GROUP: libvirt-qemu
  VOLUME_OWNER: libvirt-qemu

libvirt_vm_script_env: >-
  {{ libvirt_vm_script_env_debian | combine(libvirt_vm_virsh_default_env) }}
